export const SearchParams = {
  SECRET_KEY: "secretKey",
  PUBNET: "pubnet",
  UNTRUSTED_ASSETS: "untrustedAssets",
  ASSET_OVERRIDES: "assetOverrides",
  CLAIMABLE_BALANCE_SUPPORTED: "claimableBalanceSupported",
};

export const AssetCategory = {
  TRUSTED: "trusted",
  UNTRUSTED: "untrusted",
};

export const TomlFields = {
  ACCOUNTS: "ACCOUNTS",
  AUTH_SERVER: "AUTH_SERVER",
  DIRECT_PAYMENT_SERVER: "DIRECT_PAYMENT_SERVER",
  FEDERATION_SERVER: "FEDERATION_SERVER",
  HORIZON_URL: "HORIZON_URL",
  KYC_SERVER: "KYC_SERVER",
  NETWORK_PASSPHRASE: "NETWORK_PASSPHRASE",
  SIGNING_KEY: "SIGNING_KEY",
  TRANSFER_SERVER: "TRANSFER_SERVER",
  TRANSFER_SERVER_SEP0024: "TRANSFER_SERVER_SEP0024",
  URI_REQUEST_SIGNING_KEY: "URI_REQUEST_SIGNING_KEY",
  VERSION: "VERSION",
  WEB_AUTH_ENDPOINT: "WEB_AUTH_ENDPOINT",
};
